AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create: cloudfront distribution. Dependency: logs bucket, website buckets,
  acm certificate'
Parameters:
  RootDomainName:
    Type: String
    Description: Name of the root domain
    Default: example.com
  WebsiteBucketName:
    Type: String
    Description: Name of the bucket for frontend code
    Default: example.com
  WebsiteBucketRegion:
    Type: String
    Description: ' bucket region'
    Default: us-east-1
  LogsBucketName:
    Type: String
    Description: Name of the existing bucket to store logs
    Default: logsbucket
  S3OriginId:
    Type: String
    Description: S3 origin ID for cloudfront
    Default: s3-WebsiteBucketName
  AcmCertificateArn:
    Type: String
    Description: (Certificate Arn for the existing ACM certificate.
    AllowedPattern: arn:aws:acm:.*
    Default: certificateArn
Resources:
  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref 'RootDomainName'
          - !Sub 'www.${RootDomainName}'
        Enabled: true
        DefaultRootObject: index.html
        PriceClass: PriceClass_All
        HttpVersion: http2
        CustomErrorResponses:
          - ErrorCachingMinTTL: 300
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          TargetOriginId: !Ref 'S3OriginId'
          ViewerProtocolPolicy: redirect-to-https
          MinTTL: 0
          AllowedMethods:
            - HEAD
            - GET
          CachedMethods:
            - HEAD
            - GET
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          Compress: true
        Logging:
          Bucket: !Sub '${LogsBucketName}.s3.amazonaws.com'
          Prefix: !Sub '${RootDomainName}/cdn/'
        Origins:
          - DomainName: !Sub '${WebsiteBucketName}.s3-website-${WebsiteBucketRegion}.amazonaws.com'
            Id: !Ref 'S3OriginId'
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        Restrictions:
          GeoRestriction:
            RestrictionType: none
            Locations: []
        ViewerCertificate:
          AcmCertificateArn: !Ref 'AcmCertificateArn'
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.1_2016
Outputs:
  CFDistributionDomainName:
    Value: !GetAtt 'CloudfrontDistribution.DomainName'
    Export:
      Name: !Sub '${AWS::StackName}-CFDistributionDomainName'
