AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create: Route53 DNS records. Dependency: route53 hosted zone, cloudfront
  distribution'
Parameters:
  HostedZoneIdImport:
    Type: String
    Description: Import hosted zone Id exported in another stack
    Default: HostedZoneIdImportString
  CFDistributionDomainNameImport:
    Type: String
    Description: Import cloudfront distribution domain name exported in another stack
    Default: CFDistributionDomainNameImporString
  RootDomainName:
    Type: String
    Description: Name of the root domain
    Default: example.com
Resources:
  DNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !ImportValue
        Ref: HostedZoneIdImport
      RecordSets:
        - Name: !Sub '${RootDomainName}.'
          Type: AAAA
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !ImportValue
              Ref: CFDistributionDomainNameImport
        - Name: !Sub 'www.${RootDomainName}.'
          Type: AAAA
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !ImportValue
              Ref: CFDistributionDomainNameImport
        - Name: !Sub '${RootDomainName}.'
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !ImportValue
              Ref: CFDistributionDomainNameImport
        - Name: !Sub 'www.${RootDomainName}.'
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !ImportValue
              Ref: CFDistributionDomainNameImport
