AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create: Route53 hosted zone. Dependency: Registered domain'
Parameters:
  HostedZoneName:
    Type: String
    Description: Name of the hosted zone
    Default: example.com
Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref 'HostedZoneName'
      HostedZoneConfig:
        Comment: HostedZone created by user
Outputs:
  HostedZoneId:
    Value: !Ref 'HostedZone'
    Export:
      Name: !Sub '${AWS::StackName}-HostedZoneId'
