AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates two s3 website buckets. Dependency: logs bucket.'
Parameters:
  WebsiteBucketName:
    Type: String
    Description: Name of the bucket for frontend code
    Default: example.com
  WebsiteBucketRegion:
    Type: String
    Description: ' bucket region'
    Default: us-east-1
  LogsBucketName:
    Type: String
    Description: Name of the existing bucket to store logs
    Default: logsbucket
Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref 'WebsiteBucketName'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      AccessControl: PublicRead
      LoggingConfiguration:
        DestinationBucketName: !Ref 'LogsBucketName'
        LogFilePrefix: !Sub '${RootDomainName}/s3/'
  WWWWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'www.${WebsiteBucketName}'
      AccessControl: PublicRead
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref 'WebsiteBucket'
