AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create: Route53 hosted zone and DNS records for github. Dependency:
  github pages.'
Parameters:
  RootDomainName:
    Type: String
    Description: Name of the root domain
    Default: example.com
  GithubDomainName:
    Type: String
    Description: Name of the rootgithub-pages root domain
    Default: example.github.io
Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Sub '${RootDomainName}.'
      HostedZoneConfig:
        Comment: HostedZone created by user
  DNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref 'HostedZone'
      RecordSets:
        - Name: !Sub '${RootDomainName}.'
          Type: A
          TTL: '900'
          ResourceRecords:
            - 192.30.252.153
            - 192.30.252.154
        - Name: !Sub 'www.${RootDomainName}.'
          Type: CNAME
          TTL: '900'
          ResourceRecords:
            - !Ref 'GithubDomainName'
